version: '3'

services:
  # Create frontend container
  frontend: # Name of service
    build: ./frontend # Path to Dockerfile
    ports: # Port binding to host from Docker container
      - "8080:80" # Bind port 8080 of host to 80 of container
    container_name: ng-frontend
    restart: always
    links:
      - backend
    volumes:
      - ./frontend/site-content:/usr/share/nginx/html
  
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: ng-backend
    restart: always
    links:
      - database
  
  database:
    build: ./database
    container_name: ng-database
    restart: always
